/** Every icon the picker offers. The server validates against ICON_KEYS,
 *  and ICON_LABELS supplies each link's accessible name now that the blocks
 *  show no visible text.
 *
 *  Generated list — add a key here and a component in
 *  components/arcade/icons.tsx to extend it. */
export const ICON_KEYS = [
  "1password",
  "airbnb",
  "amazon",
  "android",
  "angular",
  "anilist",
  "apple",
  "applemusic",
  "appstore",
  "archiveofourown",
  "archlinux",
  "arduino",
  "artstation",
  "audiomack",
  "bandcamp",
  "behance",
  "bell",
  "binance",
  "bitbucket",
  "bitcoin",
  "bitcoinfa",
  "bitwarden",
  "blender",
  "blogger",
  "bluesky",
  "bolt",
  "book",
  "bots",
  "box",
  "brain",
  "brave",
  "buffer",
  "buymeacoffee",
  "calendar",
  "calendly",
  "cardano",
  "carrd",
  "cashapp",
  "chainlink",
  "chart",
  "chat",
  "chrome",
  "cloudflare",
  "code",
  "codepen",
  "codesandbox",
  "coinbase",
  "coinmarketcap",
  "confluence",
  "coursera",
  "creativecommons",
  "crown",
  "crunchbase",
  "cube",
  "dailymotion",
  "dashlane",
  "database",
  "debian",
  "devdotto",
  "deviantart",
  "digitalocean",
  "discord",
  "django",
  "docker",
  "dogecoin",
  "download",
  "dribbble",
  "dropbox",
  "drupal",
  "duolingo",
  "ebay",
  "edge",
  "element",
  "email",
  "epicgames",
  "ethereum",
  "etsy",
  "eye",
  "facebook",
  "fdroid",
  "figma",
  "file",
  "fire",
  "firebase",
  "firefox",
  "fiverr",
  "flask",
  "flickr",
  "foursquare",
  "framer",
  "game",
  "garmin",
  "ghost",
  "gift",
  "github",
  "gitlab",
  "gmail",
  "go",
  "godotengine",
  "goodreads",
  "googledocs",
  "googledrive",
  "googlemeet",
  "googleplay",
  "googlewallet",
  "gumroad",
  "hashnode",
  "heart",
  "hey",
  "hootsuite",
  "huggingface",
  "imdb",
  "indiehackers",
  "instagram",
  "internetexplorer",
  "itchdotio",
  "itunes",
  "javascript",
  "jira",
  "joomla",
  "jsfiddle",
  "kaggle",
  "key",
  "khanacademy",
  "kick",
  "kofi",
  "kubernetes",
  "laravel",
  "lastdotfm",
  "leetcode",
  "letterboxd",
  "line",
  "link",
  "linkedin",
  "linktree",
  "linux",
  "litecoin",
  "location",
  "lock",
  "magento",
  "mailchimp",
  "mastodon",
  "matrix",
  "medium",
  "meetup",
  "mixcloud",
  "monero",
  "money",
  "music",
  "myanimelist",
  "napster",
  "netlify",
  "nextdotjs",
  "nike",
  "nodedotjs",
  "notion",
  "obsidian",
  "odysee",
  "opencollective",
  "opensea",
  "opera",
  "optimism",
  "patreon",
  "paypal",
  "peertube",
  "phone",
  "photo",
  "php",
  "pinterest",
  "playstation",
  "polkadot",
  "polygon",
  "polywork",
  "producthunt",
  "protonmail",
  "python",
  "qq",
  "quora",
  "railway",
  "raspberrypi",
  "react",
  "reddit",
  "render",
  "replit",
  "revolut",
  "roamresearch",
  "roblox",
  "rocket",
  "rubyonrails",
  "rumble",
  "rust",
  "safari",
  "server",
  "shop",
  "shopify",
  "shopifyfa",
  "signal",
  "simplex",
  "site",
  "sketch",
  "skull",
  "skype",
  "slack",
  "snapchat",
  "solana",
  "soundcloud",
  "spotify",
  "squarespace",
  "stackoverflow",
  "star",
  "steam",
  "strava",
  "stripe",
  "stripefa",
  "substack",
  "supabase",
  "svelte",
  "telegram",
  "terminal",
  "tether",
  "threads",
  "ticket",
  "tidal",
  "tiktok",
  "torproject",
  "tradingview",
  "trello",
  "trezor",
  "tumblr",
  "twitch",
  "twitter",
  "typescript",
  "uber",
  "ubuntu",
  "udemy",
  "unity",
  "unrealengine",
  "unsplash",
  "upwork",
  "venmo",
  "vercel",
  "viber",
  "video",
  "vimeo",
  "vine",
  "vk",
  "vuedotjs",
  "wallet",
  "webflow",
  "weibo",
  "weixin",
  "whatsapp",
  "wikipedia",
  "windows",
  "wise",
  "wix",
  "wordpress",
  "wordpressfa",
  "work",
  "x",
  "xbox",
  "yelp",
  "youtube",
  "zoho",
  "zoom",
] as const;

export type IconKey = (typeof ICON_KEYS)[number];

export const ICON_LABELS: Record<IconKey, string> = {
  "1password": "1Password",
  "airbnb": "Airbnb",
  "amazon": "Amazon",
  "android": "Android",
  "angular": "Angular",
  "anilist": "Anilist",
  "apple": "Apple",
  "applemusic": "Applemusic",
  "appstore": "App Store",
  "archiveofourown": "AO3",
  "archlinux": "Arch Linux",
  "arduino": "Arduino",
  "artstation": "Artstation",
  "audiomack": "Audiomack",
  "bandcamp": "Bandcamp",
  "behance": "Behance",
  "bell": "Bell",
  "binance": "Binance",
  "bitbucket": "Bitbucket",
  "bitcoin": "Bitcoin",
  "bitcoinfa": "Bitcoin (alt)",
  "bitwarden": "Bitwarden",
  "blender": "Blender",
  "blogger": "Blogger",
  "bluesky": "Bluesky",
  "bolt": "Bolt",
  "book": "Book",
  "bots": "Bot",
  "box": "Box",
  "brain": "Brain",
  "brave": "Brave",
  "buffer": "Buffer",
  "buymeacoffee": "Buy Me a Coffee",
  "calendar": "Calendar",
  "calendly": "Calendly",
  "cardano": "Cardano",
  "carrd": "Carrd",
  "cashapp": "Cashapp",
  "chainlink": "Chainlink",
  "chart": "Chart",
  "chat": "Chat",
  "chrome": "Chrome",
  "cloudflare": "Cloudflare",
  "code": "Code",
  "codepen": "CodePen",
  "codesandbox": "CodeSandbox",
  "coinbase": "Coinbase",
  "coinmarketcap": "CoinMarketCap",
  "confluence": "Confluence",
  "coursera": "Coursera",
  "creativecommons": "Creative Commons",
  "crown": "Crown",
  "crunchbase": "Crunchbase",
  "cube": "Cube",
  "dailymotion": "Dailymotion",
  "dashlane": "Dashlane",
  "database": "Database",
  "debian": "Debian",
  "devdotto": "Dev.to",
  "deviantart": "Deviantart",
  "digitalocean": "DigitalOcean",
  "discord": "Discord",
  "django": "Django",
  "docker": "Docker",
  "dogecoin": "Dogecoin",
  "download": "Download",
  "dribbble": "Dribbble",
  "dropbox": "Dropbox",
  "drupal": "Drupal",
  "duolingo": "Duolingo",
  "ebay": "Ebay",
  "edge": "Edge",
  "element": "Element",
  "email": "Email",
  "epicgames": "Epic Games",
  "ethereum": "Ethereum",
  "etsy": "Etsy",
  "eye": "Eye",
  "facebook": "Facebook",
  "fdroid": "Fdroid",
  "figma": "Figma",
  "file": "Document",
  "fire": "Fire",
  "firebase": "Firebase",
  "firefox": "Firefox",
  "fiverr": "Fiverr",
  "flask": "Flask",
  "flickr": "Flickr",
  "foursquare": "Foursquare",
  "framer": "Framer",
  "game": "Game",
  "garmin": "Garmin",
  "ghost": "Ghost",
  "gift": "Gift",
  "github": "Github",
  "gitlab": "Gitlab",
  "gmail": "Gmail",
  "go": "Go",
  "godotengine": "Godot",
  "goodreads": "Goodreads",
  "googledocs": "Google Docs",
  "googledrive": "Google Drive",
  "googlemeet": "Google Meet",
  "googleplay": "Google Play",
  "googlewallet": "Google Wallet",
  "gumroad": "Gumroad",
  "hashnode": "Hashnode",
  "heart": "Heart",
  "hey": "Hey",
  "hootsuite": "Hootsuite",
  "huggingface": "Hugging Face",
  "imdb": "Imdb",
  "indiehackers": "Indie Hackers",
  "instagram": "Instagram",
  "internetexplorer": "Internet Explorer",
  "itchdotio": "itch.io",
  "itunes": "Itunes",
  "javascript": "Javascript",
  "jira": "Jira",
  "joomla": "Joomla",
  "jsfiddle": "JSFiddle",
  "kaggle": "Kaggle",
  "key": "Key",
  "khanacademy": "Khan Academy",
  "kick": "Kick",
  "kofi": "Ko-fi",
  "kubernetes": "Kubernetes",
  "laravel": "Laravel",
  "lastdotfm": "Last.fm",
  "leetcode": "LeetCode",
  "letterboxd": "Letterboxd",
  "line": "Line",
  "link": "Generic link",
  "linkedin": "Linkedin",
  "linktree": "Linktree",
  "linux": "Linux",
  "litecoin": "Litecoin",
  "location": "Location",
  "lock": "Lock",
  "magento": "Magento",
  "mailchimp": "Mailchimp",
  "mastodon": "Mastodon",
  "matrix": "Matrix",
  "medium": "Medium",
  "meetup": "Meetup",
  "mixcloud": "Mixcloud",
  "monero": "Monero",
  "money": "Money",
  "music": "Music",
  "myanimelist": "MyAnimeList",
  "napster": "Napster",
  "netlify": "Netlify",
  "nextdotjs": "Next.js",
  "nike": "Nike",
  "nodedotjs": "Node.js",
  "notion": "Notion",
  "obsidian": "Obsidian",
  "odysee": "Odysee",
  "opencollective": "Open Collective",
  "opensea": "Opensea",
  "opera": "Opera",
  "optimism": "Optimism",
  "patreon": "Patreon",
  "paypal": "Paypal",
  "peertube": "Peertube",
  "phone": "Phone",
  "photo": "Photo",
  "php": "Php",
  "pinterest": "Pinterest",
  "playstation": "Playstation",
  "polkadot": "Polkadot",
  "polygon": "Polygon",
  "polywork": "Polywork",
  "producthunt": "Product Hunt",
  "protonmail": "Proton Mail",
  "python": "Python",
  "qq": "Qq",
  "quora": "Quora",
  "railway": "Railway",
  "raspberrypi": "Raspberry Pi",
  "react": "React",
  "reddit": "Reddit",
  "render": "Render",
  "replit": "Replit",
  "revolut": "Revolut",
  "roamresearch": "Roamresearch",
  "roblox": "Roblox",
  "rocket": "Rocket",
  "rubyonrails": "Ruby on Rails",
  "rumble": "Rumble",
  "rust": "Rust",
  "safari": "Safari",
  "server": "Server",
  "shop": "Shop",
  "shopify": "Shopify",
  "shopifyfa": "Shopify (alt)",
  "signal": "Signal",
  "simplex": "Simplex",
  "site": "Website",
  "sketch": "Sketch",
  "skull": "Skull",
  "skype": "Skype",
  "slack": "Slack",
  "snapchat": "Snapchat",
  "solana": "Solana",
  "soundcloud": "Soundcloud",
  "spotify": "Spotify",
  "squarespace": "Squarespace",
  "stackoverflow": "Stack Overflow",
  "star": "Star",
  "steam": "Steam",
  "strava": "Strava",
  "stripe": "Stripe",
  "stripefa": "Stripe (alt)",
  "substack": "Substack",
  "supabase": "Supabase",
  "svelte": "Svelte",
  "telegram": "Telegram",
  "terminal": "Terminal",
  "tether": "Tether",
  "threads": "Threads",
  "ticket": "Ticket",
  "tidal": "Tidal",
  "tiktok": "Tiktok",
  "torproject": "Tor",
  "tradingview": "TradingView",
  "trello": "Trello",
  "trezor": "Trezor",
  "tumblr": "Tumblr",
  "twitch": "Twitch",
  "twitter": "Twitter",
  "typescript": "Typescript",
  "uber": "Uber",
  "ubuntu": "Ubuntu",
  "udemy": "Udemy",
  "unity": "Unity",
  "unrealengine": "Unreal Engine",
  "unsplash": "Unsplash",
  "upwork": "Upwork",
  "venmo": "Venmo",
  "vercel": "Vercel",
  "viber": "Viber",
  "video": "Video",
  "vimeo": "Vimeo",
  "vine": "Vine",
  "vk": "Vk",
  "vuedotjs": "Vue.js",
  "wallet": "Wallet",
  "webflow": "Webflow",
  "weibo": "Weibo",
  "weixin": "Weixin",
  "whatsapp": "Whatsapp",
  "wikipedia": "Wikipedia",
  "windows": "Windows",
  "wise": "Wise",
  "wix": "Wix",
  "wordpress": "Wordpress",
  "wordpressfa": "WordPress (alt)",
  "work": "Work",
  "x": "X",
  "xbox": "Xbox",
  "yelp": "Yelp",
  "youtube": "Youtube",
  "zoho": "Zoho",
  "zoom": "Zoom",
};

export function labelForIcon(key: string): string {
  return ICON_LABELS[key as IconKey] ?? "Link";
}
