import type { IconType } from "react-icons";
import {
  FaAirbnb,
  FaAmazon,
  FaArtstation,
  FaBell,
  FaBitcoin,
  FaBolt,
  FaBookOpen,
  FaRobot,
  FaBrain,
  FaCalendar,
  FaChartLine,
  FaComments,
  FaChrome,
  FaCode,
  FaCodepen,
  FaConfluence,
  FaCreativeCommons,
  FaCrown,
  FaCube,
  FaDatabase,
  FaDeviantart,
  FaDownload,
  FaDrupal,
  FaEdge,
  FaEnvelope,
  FaEye,
  FaFileLines,
  FaFire,
  FaFlickr,
  FaFoursquare,
  FaGamepad,
  FaGift,
  FaGoogleWallet,
  FaHeart,
  FaInternetExplorer,
  FaItunes,
  FaJira,
  FaJoomla,
  FaKey,
  FaLine,
  FaLink,
  FaLinkedin,
  FaLocationDot,
  FaLock,
  FaMagento,
  FaMeetup,
  FaCoins,
  FaMusic,
  FaNapster,
  FaOpera,
  FaPhone,
  FaCamera,
  FaQq,
  FaRocket,
  FaSafari,
  FaServer,
  FaCartShopping,
  FaShopify,
  FaGlobe,
  FaSkull,
  FaSkype,
  FaSlack,
  FaSquarespace,
  FaStar,
  FaStripe,
  FaTerminal,
  FaTicket,
  FaTrello,
  FaTwitter,
  FaUber,
  FaUnsplash,
  FaViber,
  FaVideo,
  FaVine,
  FaVk,
  FaWallet,
  FaWebflow,
  FaWeibo,
  FaWeixin,
  FaWindows,
  FaWix,
  FaWordpress,
  FaBriefcase,
  FaXbox,
  FaYelp,
} from "react-icons/fa6";
import {
  Si1Password,
  SiAndroid,
  SiAngular,
  SiAnilist,
  SiApple,
  SiApplemusic,
  SiAppstore,
  SiArchiveofourown,
  SiArchlinux,
  SiArduino,
  SiAudiomack,
  SiBandcamp,
  SiBehance,
  SiBinance,
  SiBitbucket,
  SiBitcoin,
  SiBitwarden,
  SiBlender,
  SiBlogger,
  SiBluesky,
  SiBox,
  SiBrave,
  SiBuffer,
  SiBuymeacoffee,
  SiCalendly,
  SiCardano,
  SiCarrd,
  SiCashapp,
  SiChainlink,
  SiCloudflare,
  SiCodesandbox,
  SiCoinbase,
  SiCoinmarketcap,
  SiCoursera,
  SiCrunchbase,
  SiDailymotion,
  SiDashlane,
  SiDebian,
  SiDevdotto,
  SiDigitalocean,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiDogecoin,
  SiDribbble,
  SiDropbox,
  SiDuolingo,
  SiEbay,
  SiElement,
  SiEpicgames,
  SiEthereum,
  SiEtsy,
  SiFacebook,
  SiFdroid,
  SiFigma,
  SiFirebase,
  SiFirefox,
  SiFiverr,
  SiFlask,
  SiFramer,
  SiGarmin,
  SiGhost,
  SiGithub,
  SiGitlab,
  SiGmail,
  SiGo,
  SiGodotengine,
  SiGoodreads,
  SiGoogledocs,
  SiGoogledrive,
  SiGooglemeet,
  SiGoogleplay,
  SiGumroad,
  SiHashnode,
  SiHey,
  SiHootsuite,
  SiHuggingface,
  SiImdb,
  SiIndiehackers,
  SiInstagram,
  SiItchdotio,
  SiJavascript,
  SiJsfiddle,
  SiKaggle,
  SiKhanacademy,
  SiKick,
  SiKofi,
  SiKubernetes,
  SiLaravel,
  SiLastdotfm,
  SiLeetcode,
  SiLetterboxd,
  SiLinktree,
  SiLinux,
  SiLitecoin,
  SiMailchimp,
  SiMastodon,
  SiMatrix,
  SiMedium,
  SiMixcloud,
  SiMonero,
  SiMyanimelist,
  SiNetlify,
  SiNextdotjs,
  SiNike,
  SiNodedotjs,
  SiNotion,
  SiObsidian,
  SiOdysee,
  SiOpencollective,
  SiOpensea,
  SiOptimism,
  SiPatreon,
  SiPaypal,
  SiPeertube,
  SiPhp,
  SiPinterest,
  SiPlaystation,
  SiPolkadot,
  SiPolygon,
  SiPolywork,
  SiProducthunt,
  SiProtonmail,
  SiPython,
  SiQuora,
  SiRailway,
  SiRaspberrypi,
  SiReact,
  SiReddit,
  SiRender,
  SiReplit,
  SiRevolut,
  SiRoamresearch,
  SiRoblox,
  SiRubyonrails,
  SiRumble,
  SiRust,
  SiShopify,
  SiSignal,
  SiSimplex,
  SiSketch,
  SiSnapchat,
  SiSolana,
  SiSoundcloud,
  SiSpotify,
  SiStackoverflow,
  SiSteam,
  SiStrava,
  SiStripe,
  SiSubstack,
  SiSupabase,
  SiSvelte,
  SiTelegram,
  SiTether,
  SiThreads,
  SiTidal,
  SiTiktok,
  SiTorproject,
  SiTradingview,
  SiTrezor,
  SiTumblr,
  SiTwitch,
  SiTypescript,
  SiUbuntu,
  SiUdemy,
  SiUnity,
  SiUnrealengine,
  SiUpwork,
  SiVenmo,
  SiVercel,
  SiVimeo,
  SiVuedotjs,
  SiWhatsapp,
  SiWikipedia,
  SiWise,
  SiWordpress,
  SiX,
  SiYoutube,
  SiZoho,
  SiZoom,
} from "react-icons/si";
import { ICON_KEYS, ICON_LABELS, type IconKey } from "@/lib/icon-keys";

export const ICONS: Record<IconKey, IconType> = {
  "1password": Si1Password,
  "airbnb": FaAirbnb,
  "amazon": FaAmazon,
  "android": SiAndroid,
  "angular": SiAngular,
  "anilist": SiAnilist,
  "apple": SiApple,
  "applemusic": SiApplemusic,
  "appstore": SiAppstore,
  "archiveofourown": SiArchiveofourown,
  "archlinux": SiArchlinux,
  "arduino": SiArduino,
  "artstation": FaArtstation,
  "audiomack": SiAudiomack,
  "bandcamp": SiBandcamp,
  "behance": SiBehance,
  "bell": FaBell,
  "binance": SiBinance,
  "bitbucket": SiBitbucket,
  "bitcoin": SiBitcoin,
  "bitcoinfa": FaBitcoin,
  "bitwarden": SiBitwarden,
  "blender": SiBlender,
  "blogger": SiBlogger,
  "bluesky": SiBluesky,
  "bolt": FaBolt,
  "book": FaBookOpen,
  "bots": FaRobot,
  "box": SiBox,
  "brain": FaBrain,
  "brave": SiBrave,
  "buffer": SiBuffer,
  "buymeacoffee": SiBuymeacoffee,
  "calendar": FaCalendar,
  "calendly": SiCalendly,
  "cardano": SiCardano,
  "carrd": SiCarrd,
  "cashapp": SiCashapp,
  "chainlink": SiChainlink,
  "chart": FaChartLine,
  "chat": FaComments,
  "chrome": FaChrome,
  "cloudflare": SiCloudflare,
  "code": FaCode,
  "codepen": FaCodepen,
  "codesandbox": SiCodesandbox,
  "coinbase": SiCoinbase,
  "coinmarketcap": SiCoinmarketcap,
  "confluence": FaConfluence,
  "coursera": SiCoursera,
  "creativecommons": FaCreativeCommons,
  "crown": FaCrown,
  "crunchbase": SiCrunchbase,
  "cube": FaCube,
  "dailymotion": SiDailymotion,
  "dashlane": SiDashlane,
  "database": FaDatabase,
  "debian": SiDebian,
  "devdotto": SiDevdotto,
  "deviantart": FaDeviantart,
  "digitalocean": SiDigitalocean,
  "discord": SiDiscord,
  "django": SiDjango,
  "docker": SiDocker,
  "dogecoin": SiDogecoin,
  "download": FaDownload,
  "dribbble": SiDribbble,
  "dropbox": SiDropbox,
  "drupal": FaDrupal,
  "duolingo": SiDuolingo,
  "ebay": SiEbay,
  "edge": FaEdge,
  "element": SiElement,
  "email": FaEnvelope,
  "epicgames": SiEpicgames,
  "ethereum": SiEthereum,
  "etsy": SiEtsy,
  "eye": FaEye,
  "facebook": SiFacebook,
  "fdroid": SiFdroid,
  "figma": SiFigma,
  "file": FaFileLines,
  "fire": FaFire,
  "firebase": SiFirebase,
  "firefox": SiFirefox,
  "fiverr": SiFiverr,
  "flask": SiFlask,
  "flickr": FaFlickr,
  "foursquare": FaFoursquare,
  "framer": SiFramer,
  "game": FaGamepad,
  "garmin": SiGarmin,
  "ghost": SiGhost,
  "gift": FaGift,
  "github": SiGithub,
  "gitlab": SiGitlab,
  "gmail": SiGmail,
  "go": SiGo,
  "godotengine": SiGodotengine,
  "goodreads": SiGoodreads,
  "googledocs": SiGoogledocs,
  "googledrive": SiGoogledrive,
  "googlemeet": SiGooglemeet,
  "googleplay": SiGoogleplay,
  "googlewallet": FaGoogleWallet,
  "gumroad": SiGumroad,
  "hashnode": SiHashnode,
  "heart": FaHeart,
  "hey": SiHey,
  "hootsuite": SiHootsuite,
  "huggingface": SiHuggingface,
  "imdb": SiImdb,
  "indiehackers": SiIndiehackers,
  "instagram": SiInstagram,
  "internetexplorer": FaInternetExplorer,
  "itchdotio": SiItchdotio,
  "itunes": FaItunes,
  "javascript": SiJavascript,
  "jira": FaJira,
  "joomla": FaJoomla,
  "jsfiddle": SiJsfiddle,
  "kaggle": SiKaggle,
  "key": FaKey,
  "khanacademy": SiKhanacademy,
  "kick": SiKick,
  "kofi": SiKofi,
  "kubernetes": SiKubernetes,
  "laravel": SiLaravel,
  "lastdotfm": SiLastdotfm,
  "leetcode": SiLeetcode,
  "letterboxd": SiLetterboxd,
  "line": FaLine,
  "link": FaLink,
  "linkedin": FaLinkedin,
  "linktree": SiLinktree,
  "linux": SiLinux,
  "litecoin": SiLitecoin,
  "location": FaLocationDot,
  "lock": FaLock,
  "magento": FaMagento,
  "mailchimp": SiMailchimp,
  "mastodon": SiMastodon,
  "matrix": SiMatrix,
  "medium": SiMedium,
  "meetup": FaMeetup,
  "mixcloud": SiMixcloud,
  "monero": SiMonero,
  "money": FaCoins,
  "music": FaMusic,
  "myanimelist": SiMyanimelist,
  "napster": FaNapster,
  "netlify": SiNetlify,
  "nextdotjs": SiNextdotjs,
  "nike": SiNike,
  "nodedotjs": SiNodedotjs,
  "notion": SiNotion,
  "obsidian": SiObsidian,
  "odysee": SiOdysee,
  "opencollective": SiOpencollective,
  "opensea": SiOpensea,
  "opera": FaOpera,
  "optimism": SiOptimism,
  "patreon": SiPatreon,
  "paypal": SiPaypal,
  "peertube": SiPeertube,
  "phone": FaPhone,
  "photo": FaCamera,
  "php": SiPhp,
  "pinterest": SiPinterest,
  "playstation": SiPlaystation,
  "polkadot": SiPolkadot,
  "polygon": SiPolygon,
  "polywork": SiPolywork,
  "producthunt": SiProducthunt,
  "protonmail": SiProtonmail,
  "python": SiPython,
  "qq": FaQq,
  "quora": SiQuora,
  "railway": SiRailway,
  "raspberrypi": SiRaspberrypi,
  "react": SiReact,
  "reddit": SiReddit,
  "render": SiRender,
  "replit": SiReplit,
  "revolut": SiRevolut,
  "roamresearch": SiRoamresearch,
  "roblox": SiRoblox,
  "rocket": FaRocket,
  "rubyonrails": SiRubyonrails,
  "rumble": SiRumble,
  "rust": SiRust,
  "safari": FaSafari,
  "server": FaServer,
  "shop": FaCartShopping,
  "shopify": SiShopify,
  "shopifyfa": FaShopify,
  "signal": SiSignal,
  "simplex": SiSimplex,
  "site": FaGlobe,
  "sketch": SiSketch,
  "skull": FaSkull,
  "skype": FaSkype,
  "slack": FaSlack,
  "snapchat": SiSnapchat,
  "solana": SiSolana,
  "soundcloud": SiSoundcloud,
  "spotify": SiSpotify,
  "squarespace": FaSquarespace,
  "stackoverflow": SiStackoverflow,
  "star": FaStar,
  "steam": SiSteam,
  "strava": SiStrava,
  "stripe": SiStripe,
  "stripefa": FaStripe,
  "substack": SiSubstack,
  "supabase": SiSupabase,
  "svelte": SiSvelte,
  "telegram": SiTelegram,
  "terminal": FaTerminal,
  "tether": SiTether,
  "threads": SiThreads,
  "ticket": FaTicket,
  "tidal": SiTidal,
  "tiktok": SiTiktok,
  "torproject": SiTorproject,
  "tradingview": SiTradingview,
  "trello": FaTrello,
  "trezor": SiTrezor,
  "tumblr": SiTumblr,
  "twitch": SiTwitch,
  "twitter": FaTwitter,
  "typescript": SiTypescript,
  "uber": FaUber,
  "ubuntu": SiUbuntu,
  "udemy": SiUdemy,
  "unity": SiUnity,
  "unrealengine": SiUnrealengine,
  "unsplash": FaUnsplash,
  "upwork": SiUpwork,
  "venmo": SiVenmo,
  "vercel": SiVercel,
  "viber": FaViber,
  "video": FaVideo,
  "vimeo": SiVimeo,
  "vine": FaVine,
  "vk": FaVk,
  "vuedotjs": SiVuedotjs,
  "wallet": FaWallet,
  "webflow": FaWebflow,
  "weibo": FaWeibo,
  "weixin": FaWeixin,
  "whatsapp": SiWhatsapp,
  "wikipedia": SiWikipedia,
  "windows": FaWindows,
  "wise": SiWise,
  "wix": FaWix,
  "wordpress": SiWordpress,
  "wordpressfa": FaWordpress,
  "work": FaBriefcase,
  "x": SiX,
  "xbox": FaXbox,
  "yelp": FaYelp,
  "youtube": SiYoutube,
  "zoho": SiZoho,
  "zoom": SiZoom,
};

export function iconFor(key: string): IconType {
  return ICONS[key as IconKey] ?? FaLink;
}

export const ICON_OPTIONS = ICON_KEYS.map((key) => ({
  key,
  label: ICON_LABELS[key],
  Icon: ICONS[key],
}));
